test:
  name: asset-did-vc
  description: Benchmark for the asset-did-vc chaincode.
  workers:
    number: 2
  rounds:
    #- label: getAccumulator
    #  description: Test query performance of GetAccumulator.
    #  txNumber: 1000
    #  rateControl:
    #    type: fixed-load
    #    opts:
    #      transactionLoad: 1000
    #  workload:
    #    module: asset-did-vc/bench-new/getAccumulator.js
    - label: updateAccumulator
      description: Test transaction performance of UpdateAccumulator.
      txNumber: 5000
      rateControl:
        type: fixed-load
        opts:
          transactionLoad: 5000
      workload:
        module: asset-did-vc/bench-new/updateAccumulator.js
